[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "7YvhF9AKe4i7Zuha8NtqEuV2BDUqyGGqWiZvuVKdmYD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
